/**
 * Accounts constants
 */

export const CREATE_ACCOUNT_LOADING = "CREATE_ACCOUNT_LOADING";
export const CREATE_ACCOUNT_TOASTR = "CREATE_ACCOUNT_TOASTR";
export const CREATE_ACCOUNT_ERROR_MESSAGE = "CREATE_ACCOUNT_ERROR_MESSAGE";
export const CREATE_ACCOUNT = "CREATE_ACCOUNT";

export const LOGIN = "LOGIN";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_TOASTR = "LOGIN_TOASTR";
export const LOGIN_ERROR_MESSAGE = "LOGIN_ERROR_MESSAGE";

export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_LOADING = "FORGOT_PASSWORD_LOADING";
export const FORGOT_PASSWORD_TOASTR = "FORGOT_PASSWORD_TOASTR";
export const FORGOT_PASSWORD_ERROR_MESSAGE = "FORGOT_PASSWORD_ERROR_MESSAGE";
export const FORGOT_PASSWORD_CLOSE_MODAL = "FORGOT_PASSWORD_CLOSE_MODAL";
