/**
 * Customers constants
 */

export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const SET_CUSTOMERS = "SET_CUSTOMERS";
export const SET_CUSTOMERS_LOADING = "SET_CUSTOMERS_LOADING";

export const EDIT_CUSTOMER = "EDIT_CUSTOMER";
export const EDIT_CUSTOMER_SUCCESS = "EDIT_CUSTOMER_SUCCESS";
export const EDIT_CUSTOMER_ERROR_MESSAGE = "EDIT_CUSTOMER_ERROR_MESSAGE";
export const EDIT_CUSTOMER_RESET_FLAG = "EDIT_CUSTOMER_RESET_FLAG";

export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_ERROR_MESSAGE = "DELETE_CUSTOMER_ERROR_MESSAGE";
export const DELETE_CUSTOMER_RESET_FLAG = "DELETE_CUSTOMER_RESET_FLAG";