/**
 * Info cards constants
 */

export const GET_REVENUE_INFO_CARD = 'GET_REVENUE_INFO_CARD';
export const SET_REVENUE_INFO_CARD = 'SET_REVENUE_INFO_CARD';
export const SET_REVENUE_INFO_CARD_LOADING = 'SET_REVENUE_INFO_CARD_LOADING';

export const GET_TOTAL_ORDERS_INFO_CARD = 'GET_TOTAL_ORDERS_INFO_CARD';
export const SET_TOTAL_ORDERS_INFO_CARD = 'SET_TOTAL_ORDERS_INFO_CARD';
export const SET_TOTAL_ORDERS_INFO_CARD_LOADING = 'SET_TOTAL_ORDERS_INFO_CARD_LOADING';
